# Follow the outer terminal's ANSI palette, matching Herdr's `terminal` theme.
typeset -g POWERLEVEL9K_BACKGROUND=black
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND=8
typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='%F{8}|'
typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='%F{8}|'
typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=white

typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=green
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=red
typeset -g POWERLEVEL9K_DIR_FOREGROUND=blue
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=8
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=cyan

typeset -g POWERLEVEL9K_VCS_META_FOREGROUND=8
typeset -g POWERLEVEL9K_VCS_CLEAN_STATE_FOREGROUND=green
typeset -g POWERLEVEL9K_VCS_MODIFIED_STATE_FOREGROUND=yellow
typeset -g POWERLEVEL9K_VCS_UNTRACKED_STATE_FOREGROUND=cyan
typeset -g POWERLEVEL9K_VCS_CONFLICTED_STATE_FOREGROUND=red
typeset -g POWERLEVEL9K_VCS_LOADING_STATE_FOREGROUND=8
typeset -g POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_COLOR=green
typeset -g POWERLEVEL9K_VCS_LOADING_VISUAL_IDENTIFIER_COLOR=8
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=green
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=cyan
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=yellow

typeset -g POWERLEVEL9K_STATUS_OK{,_PIPE}_FOREGROUND=green
typeset -g POWERLEVEL9K_STATUS_ERROR{,_SIGNAL,_PIPE}_FOREGROUND=red
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=8
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=cyan
typeset -g POWERLEVEL9K_DIRENV_FOREGROUND=yellow
typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=white
typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=red
typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_FOREGROUND=magenta
typeset -g POWERLEVEL9K_{VIRTUALENV,ANACONDA,PYENV}_FOREGROUND=cyan
typeset -g POWERLEVEL9K_{NODENV,NVM,NODEENV,NODE_VERSION}_FOREGROUND=green
typeset -g POWERLEVEL9K_PACKAGE_FOREGROUND=magenta
typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_FOREGROUND=magenta
typeset -g POWERLEVEL9K_AWS_DEFAULT_FOREGROUND=yellow
typeset -g POWERLEVEL9K_TIME_FOREGROUND=blue
